In [20]:
import numpy as np 
import pandas as pd 

customer = pd.read_excel("C:\\Users\\rjith\\Downloads\\DATASET - NumPy MACHINE TEST.xlsx", sheet_name ='customer_data.csv')
customer = customer.iloc[:,0].str.split(',',expand = True)
sales = pd.read_excel("C:\\Users\\rjith\\Downloads\\DATASET - NumPy MACHINE TEST.xlsx",sheet_name='sales_data.csv')
noisy = pd.read_excel("C:\\Users\\rjith\\Downloads\\DATASET - NumPy MACHINE TEST.xlsx",sheet_name='noise_data.csv')
customer = customer.to_numpy()
sales = sales.to_numpy()
noisy = noisy.to_numpy()
print('Number of rows and columns:',customer.shape)
print(sales.shape)
print('Total number of values:',customer.size)
print('Number of dimensions:',customer.ndim)
print('Data type:',customer.dtype)
print('Question 4:')
print('First 5 rows:\n',customer[:5]) #Display first 5 rows
print('Last 5 rows:\n',customer[-5:]) #Display last row
print('First 1 column:\n',customer[0:]) #Display first column
print(customer[::2]) #Display every 2nd row
print(customer[0:5, 1:3]) #Display rows 0–4 and columns 1–2
print(customer[[6, 12]]) #Select specific rows like 1, 5, and 10
print('Question 5:')
print(customer[customer[:,0].astype(int) > 30]) #Get rows where first column is greater than 30
print(customer[(customer[:,0].astype(int) > 30) & (customer[:,1].astype(int) > 30)]) #Get rows where first column > 30 AND second column > 30
print('Question 6:')
print(customer * 2) #Multiply all values in the dataset by 2
result2 = np.zeros(customer.shape)
for i in range(customer.shape[0]):    
    for j in range(customer.shape[1]):  
        result2[i,j] = customer[i,j] * 2
print(result2)
print('Question 7:')
sales = sales.astype(float)
print(sales.sum(axis=0)) #Sum of each row
print(sales.mean(axis=1)) #Average of each column
print('Question 8:')
print(customer.reshape(500,10)) #changed the dataset into a different shape
print(customer.ravel()) #Convert it into a single row
print('Hstack:\n',np.hstack((customer[:50],sales))) #Combine two datasets horizontally
sales_new = np.repeat(sales, 5, axis=1)  # (50,5)
print('Vstack:\n',np.vstack((customer, sales_new)))
print('Split:\n',np.split(customer,5))
print('Question 9:')
print(np.sort(customer)) #Sort the dataset
print('max position:',customer.argmax()) #Find position of maximum value
print(customer.argmin()) #Find position of minimum value
print('Question 10:')
customer = customer.astype(float)
print(np.where(customer > 30, 1, 0))
print('Question 11:')
print('Average:\n',np.mean(sales))
print('Median:\n',np.median(sales))
print('Standard deviation:\n',np.std(sales))
print('Variance:\n',np.var(sales))
print('Cumulative sum:\n',np.cumsum(sales))
print('Question 13:')
noisy = noisy.copy()
print(np.isnan(noisy))
print(np.isinf(noisy))
noisy[np.isnan(noisy)] = 0
noisy[np.isinf(noisy)] = 0
print('Question 14:')
clean_noisy = noisy[~np.isnan(noisy)]
clean_noisy = clean_noisy[~np.isinf(clean_noisy)]
print(clean_noisy)
print('Question 15:')
small = np.array([1,2,3,4,5])
result = noisy + small
print(result)
print('Question 16: ')
copy1 = noisy.view()
copy2 = noisy.copy()
copy1[0,0] = 999
print('Changed:\n',noisy[0,0]) #changed
copy2[0,0] = 555
print(noisy[0,0]) #unchanged
print('Question 17:')
np.save("noisy_data.npy", noisy) # Save as binary
binary_data = np.load("noisy_data.npy")
print(binary_data)
np.savetxt("noisy_data.txt", noisy) # Save as text
text_data = np.loadtxt("noisy_data.txt")
print(text_data)
print('Question 19:')
noisy = noisy.copy()
noisy = np.nan_to_num(noisy,nan=0, posinf=0,neginf=0)
print("Missing values present:", np.isnan(noisy).any())
print("Infinite values present:", np.isinf(noisy).any())
print("Dataset mean:", np.mean(noisy))


Number of rows and columns: (1000, 5)
(50, 1)
Total number of values: 5000
Number of dimensions: 2
Data type: object
Question 4:
First 5 rows:
 [['56' '46' '32' '25' '38']
 ['56' '36' '40' '28' '28']
 ['41' '53' '57' '41' '20']
 ['39' '19' '41' '47' '55']
 ['19' '38' '50' '29' '39']]
Last 5 rows:
 [['52' '23' '22' '39' '40']
 ['42' '51' '43' '22' '43']
 ['37' '23' '23' '35' '21']
 ['34' '31' '31' '30' '24']
 ['32' '36' '52' '34' '52']]
First 1 column:
 [['56' '46' '32' '25' '38']
 ['56' '36' '40' '28' '28']
 ['41' '53' '57' '41' '20']
 ...
 ['37' '23' '23' '35' '21']
 ['34' '31' '31' '30' '24']
 ['32' '36' '52' '34' '52']]
[['56' '46' '32' '25' '38']
 ['41' '53' '57' '41' '20']
 ['19' '38' '50' '29' '39']
 ...
 ['25' '32' '44' '30' '48']
 ['42' '51' '43' '22' '43']
 ['34' '31' '31' '30' '24']]
[['46' '32']
 ['36' '40']
 ['53' '57']
 ['19' '41']
 ['38' '50']]
[['32' '20' '54' '24' '38']
 ['43' '51' '27' '53' '31']]
Question 5:
[['56' '46' '32' '25' '38']
 ['56' '36' '40' '28' '28']
 ['4

In [1]:
import numpy as np 

print('Question 2:')

print('Zeros:\n',np.zeros((3,3)))
print('Ones:\n',np.ones((3,3)))
print('Full:\n',np.full((3,3),12))
print('Arange:\n',np.arange(1,10,2))
print('Linspace:\n',np.linspace(0,1,5))
print('Eye:\n',np.eye(3))
print('Diagonal:\n',np.diag([3,4,5]))
print('Question 3:')
print('Random:\n',np.random.rand(4))
print('Randomn\n',np.random.randn(5))
print('Question 12:')
A = np.array([[2,1],[1,3]])
print('Multiply')
print(A @ A)
print('Determinant')
print(np.linalg.det(A))
print('Inverse')
print(np.linalg.inv(A))
print('Equations')
b = np.array([5,6])
solution = np.linalg.solve(A,b)
print(solution)
print('Question 18:')
import numpy as np
image = np.array([[ 50,120,200,255, 30],[ 80,140,220,240, 60],[100,160,180,210, 90],[ 70,130,190,230,110],[ 40,150,170,250,125]])
print(image)
normalized = image / 255
print(normalized)


Question 2:
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full:
 [[12 12 12]
 [12 12 12]
 [12 12 12]]
Arange:
 [1 3 5 7 9]
Linspace:
 [0.   0.25 0.5  0.75 1.  ]
Eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Diagonal:
 [[3 0 0]
 [0 4 0]
 [0 0 5]]
Question 3:
Random:
 [0.92693069 0.45935572 0.43437065 0.09416233]
Randomn
 [-0.48306615 -1.33312936 -0.81000448  0.25838696  0.88776038]
Question 12:
Multiply
[[ 5  5]
 [ 5 10]]
Determinant
5.000000000000001
Inverse
[[ 0.6 -0.2]
 [-0.2  0.4]]
Equations
[1.8 1.4]
Question 18:
[[ 50 120 200 255  30]
 [ 80 140 220 240  60]
 [100 160 180 210  90]
 [ 70 130 190 230 110]
 [ 40 150 170 250 125]]
[[0.19607843 0.47058824 0.78431373 1.         0.11764706]
 [0.31372549 0.54901961 0.8627451  0.94117647 0.23529412]
 [0.39215686 0.62745098 0.70588235 0.82352941 0.35294118]
 [0.2745098  0.50980392 0.74509804 0.90196078 0.43137255]
 [0.15686275 0.58823529 0.66666667 0.98039216 0.49019608]]
